//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fab.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fab.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Account.
        /// </summary>
        public static string AccountsDashboardView_CreateAccount {
            get {
                return ResourceManager.GetString("AccountsDashboardView_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts ({0}).
        /// </summary>
        public static string AccountsDashboardView_Name_Counts {
            get {
                return ResourceManager.GetString("AccountsDashboardView_Name_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AccountView_Delete {
            get {
                return ResourceManager.GetString("AccountView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete account &apos;{0}&apos;?.
        /// </summary>
        public static string AccountView_Delete_Confirmation_Message {
            get {
                return ResourceManager.GetString("AccountView_Delete_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string AccountView_Delete_Confirmation_Title {
            get {
                return ResourceManager.GetString("AccountView_Delete_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AccountView_Edit {
            get {
                return ResourceManager.GetString("AccountView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First posting on.
        /// </summary>
        public static string AccountView_FirstPostingOn {
            get {
                return ResourceManager.GetString("AccountView_FirstPostingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last posting on.
        /// </summary>
        public static string AccountView_LastPostingOn {
            get {
                return ResourceManager.GetString("AccountView_LastPostingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postings count.
        /// </summary>
        public static string AccountView_PostingsCount {
            get {
                return ResourceManager.GetString("AccountView_PostingsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories ({0}).
        /// </summary>
        public static string CategoriesDashBoardView_Name_Counts {
            get {
                return ResourceManager.GetString("CategoriesDashBoardView_Name_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common categories.
        /// </summary>
        public static string CategoriesView_CommonCategories {
            get {
                return ResourceManager.GetString("CategoriesView_CommonCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Category.
        /// </summary>
        public static string CategoriesView_CreateNew {
            get {
                return ResourceManager.GetString("CategoriesView_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit categories.
        /// </summary>
        public static string CategoriesView_DepositCategories {
            get {
                return ResourceManager.GetString("CategoriesView_DepositCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string CategoriesView_Used {
            get {
                return ResourceManager.GetString("CategoriesView_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal categories.
        /// </summary>
        public static string CategoriesView_WithdrawalCategories {
            get {
                return ResourceManager.GetString("CategoriesView_WithdrawalCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CategoryView_Delete {
            get {
                return ResourceManager.GetString("CategoryView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete category &apos;{0}&apos;?.
        /// </summary>
        public static string CategoryView_Delete_Confirmation_Message {
            get {
                return ResourceManager.GetString("CategoryView_Delete_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string CategoryView_Delete_Confirmation_Title {
            get {
                return ResourceManager.GetString("CategoryView_Delete_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CategoryView_Edit {
            get {
                return ResourceManager.GetString("CategoryView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not responding. Please try again later..
        /// </summary>
        public static string Error_Service_Is_Not_Responding {
            get {
                return ResourceManager.GetString("Error_Service_Is_Not_Responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is too busy. Please try again later..
        /// </summary>
        public static string Error_Service_Is_Too_Busy {
            get {
                return ResourceManager.GetString("Error_Service_Is_Too_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loader_Loading {
            get {
                return ResourceManager.GetString("Loader_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string LoginView_Authorization_In_Progress {
            get {
                return ResourceManager.GetString("LoginView_Authorization_In_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LoginView_Language {
            get {
                return ResourceManager.GetString("LoginView_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember name.
        /// </summary>
        public static string LoginView_Remember_me {
            get {
                return ResourceManager.GetString("LoginView_Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string LoginView_Show_characters {
            get {
                return ResourceManager.GetString("LoginView_Show_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginView_Username {
            get {
                return ResourceManager.GetString("LoginView_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageBoxView_Cancel {
            get {
                return ResourceManager.GetString("MessageBoxView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBoxView_No {
            get {
                return ResourceManager.GetString("MessageBoxView_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageBoxView_Ok {
            get {
                return ResourceManager.GetString("MessageBoxView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBoxView_Yes {
            get {
                return ResourceManager.GetString("MessageBoxView_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string NewAccountView_AccountName {
            get {
                return ResourceManager.GetString("NewAccountView_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset type.
        /// </summary>
        public static string NewAccountView_AssetType {
            get {
                return ResourceManager.GetString("NewAccountView_AssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewAccountView_Cancel {
            get {
                return ResourceManager.GetString("NewAccountView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string NewAccountView_Edit {
            get {
                return ResourceManager.GetString("NewAccountView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewAccountView_New {
            get {
                return ResourceManager.GetString("NewAccountView_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NewAccountView_Save {
            get {
                return ResourceManager.GetString("NewAccountView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewCategoryView_Cancel {
            get {
                return ResourceManager.GetString("NewCategoryView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string NewCategoryView_CategoryName {
            get {
                return ResourceManager.GetString("NewCategoryView_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string NewCategoryView_Edit {
            get {
                return ResourceManager.GetString("NewCategoryView_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string NewCategoryView_New {
            get {
                return ResourceManager.GetString("NewCategoryView_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NewCategoryView_Save {
            get {
                return ResourceManager.GetString("NewCategoryView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NewCategoryView_Type {
            get {
                return ResourceManager.GetString("NewCategoryView_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string PersonalCornerView_Sign_out {
            get {
                return ResourceManager.GetString("PersonalCornerView_Sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Expense.
        /// </summary>
        public static string PostingActionsView_NewExpense {
            get {
                return ResourceManager.GetString("PostingActionsView_NewExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Income.
        /// </summary>
        public static string PostingActionsView_NewIncome {
            get {
                return ResourceManager.GetString("PostingActionsView_NewIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Transfer.
        /// </summary>
        public static string PostingActionsView_NewTransfer {
            get {
                return ResourceManager.GetString("PostingActionsView_NewTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string PostingsFilterView_Today {
            get {
                return ResourceManager.GetString("PostingsFilterView_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string PostingsView_Column_Balance {
            get {
                return ResourceManager.GetString("PostingsView_Column_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string PostingsView_Column_Category {
            get {
                return ResourceManager.GetString("PostingsView_Column_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PostingsView_Column_Comment {
            get {
                return ResourceManager.GetString("PostingsView_Column_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PostingsView_Column_Date {
            get {
                return ResourceManager.GetString("PostingsView_Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PostingsView_Column_Delete {
            get {
                return ResourceManager.GetString("PostingsView_Column_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PostingsView_Column_Edit {
            get {
                return ResourceManager.GetString("PostingsView_Column_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string PostingsView_Column_Expense {
            get {
                return ResourceManager.GetString("PostingsView_Column_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PostingsView_Column_Id {
            get {
                return ResourceManager.GetString("PostingsView_Column_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string PostingsView_Column_Income {
            get {
                return ResourceManager.GetString("PostingsView_Column_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference:.
        /// </summary>
        public static string PostingsView_Difference {
            get {
                return ResourceManager.GetString("PostingsView_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End balance:.
        /// </summary>
        public static string PostingsView_End_Balance {
            get {
                return ResourceManager.GetString("PostingsView_End_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense:.
        /// </summary>
        public static string PostingsView_Expense {
            get {
                return ResourceManager.GetString("PostingsView_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string PostingsView_Filter_Days {
            get {
                return ResourceManager.GetString("PostingsView_Filter_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income:.
        /// </summary>
        public static string PostingsView_Income {
            get {
                return ResourceManager.GetString("PostingsView_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postings:.
        /// </summary>
        public static string PostingsView_Postings {
            get {
                return ResourceManager.GetString("PostingsView_Postings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start balance:.
        /// </summary>
        public static string PostingsView_Start_Balance {
            get {
                return ResourceManager.GetString("PostingsView_Start_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected posting #{0} ?.
        /// </summary>
        public static string PostingViewModelBase_DeleteConfirmation_Message {
            get {
                return ResourceManager.GetString("PostingViewModelBase_DeleteConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string PostingViewModelBase_DeleteConfirmation_Title {
            get {
                return ResourceManager.GetString("PostingViewModelBase_DeleteConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string PostingViewModelBase_SearchStatus_Search {
            get {
                return ResourceManager.GetString("PostingViewModelBase_SearchStatus_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string PostingViewModelBase_SearchStatus_Searching {
            get {
                return ResourceManager.GetString("PostingViewModelBase_SearchStatus_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the.
        /// </summary>
        public static string RegistrationView_Agreement1 {
            get {
                return ResourceManager.GetString("RegistrationView_Agreement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nReez terms and conditions.
        /// </summary>
        public static string RegistrationView_Agreement2 {
            get {
                return ResourceManager.GetString("RegistrationView_Agreement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegistrationView_Password {
            get {
                return ResourceManager.GetString("RegistrationView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (again).
        /// </summary>
        public static string RegistrationView_Password2 {
            get {
                return ResourceManager.GetString("RegistrationView_Password2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string RegistrationView_Register {
            get {
                return ResourceManager.GetString("RegistrationView_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing up....
        /// </summary>
        public static string RegistrationView_Registration_In_Progress {
            get {
                return ResourceManager.GetString("RegistrationView_Registration_In_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string RegistrationView_Title {
            get {
                return ResourceManager.GetString("RegistrationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string RegistrationView_Username {
            get {
                return ResourceManager.GetString("RegistrationView_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to close application window manually, since the application does not have the Elevated Permissions (required to close its main window by himself)..
        /// </summary>
        public static string ScreensBootstrapper_Close_Notification_Message {
            get {
                return ResourceManager.GetString("ScreensBootstrapper_Close_Notification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string ScreensBootstrapper_Close_Notification_Title {
            get {
                return ResourceManager.GetString("ScreensBootstrapper_Close_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application update is available, but it requires a new version of Silverlight. Please contact tech support for further instructions..
        /// </summary>
        public static string ScreensBootstrapper_Update_Notification_Error {
            get {
                return ResourceManager.GetString("ScreensBootstrapper_Update_Notification_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been updated! Please close and reopen it to load the new version..
        /// </summary>
        public static string ScreensBootstrapper_Update_Notification_Message {
            get {
                return ResourceManager.GetString("ScreensBootstrapper_Update_Notification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string ScreensBootstrapper_Update_Notification_Title {
            get {
                return ResourceManager.GetString("ScreensBootstrapper_Update_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string SearchDashBoardView_Charts_LegendTitle {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Charts_LegendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string SearchDashBoardView_Charts_Line1 {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Charts_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string SearchDashBoardView_Charts_Line2 {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Charts_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string SearchDashBoardView_Charts_Title {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Charts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string SearchDashBoardView_Column_Category {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string SearchDashBoardView_Column_Comment {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SearchDashBoardView_Column_Date {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SearchDashBoardView_Column_Delete {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SearchDashBoardView_Column_Edit {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string SearchDashBoardView_Column_Expense {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string SearchDashBoardView_Column_Id {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string SearchDashBoardView_Column_Income {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Column_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains text:.
        /// </summary>
        public static string SearchDashBoardView_Contains {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference:.
        /// </summary>
        public static string SearchDashBoardView_Difference {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense:.
        /// </summary>
        public static string SearchDashBoardView_Expense {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string SearchDashBoardView_Filter_End {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Filter_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SearchDashBoardView_Filter_Start {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Filter_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income:.
        /// </summary>
        public static string SearchDashBoardView_Income {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchDashBoardView_Name_Empty {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ({0}).
        /// </summary>
        public static string SearchDashBoardView_Name_Results {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Name_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postings:.
        /// </summary>
        public static string SearchDashBoardView_Postings {
            get {
                return ResourceManager.GetString("SearchDashBoardView_Postings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Login.
        /// </summary>
        public static string StartView_back_to_Login {
            get {
                return ResourceManager.GetString("StartView_back_to_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up ».
        /// </summary>
        public static string StartView_or_Sign_up {
            get {
                return ResourceManager.GetString("StartView_or_Sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string TransactionView_Amount {
            get {
                return ResourceManager.GetString("TransactionView_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TransactionView_Cancel {
            get {
                return ResourceManager.GetString("TransactionView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TransactionView_Category {
            get {
                return ResourceManager.GetString("TransactionView_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TransactionView_Comment {
            get {
                return ResourceManager.GetString("TransactionView_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TransactionView_Date {
            get {
                return ResourceManager.GetString("TransactionView_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string TransactionView_Price {
            get {
                return ResourceManager.GetString("TransactionView_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string TransactionView_Quantity {
            get {
                return ResourceManager.GetString("TransactionView_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TransactionView_Save {
            get {
                return ResourceManager.GetString("TransactionView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string TransferView_Amount {
            get {
                return ResourceManager.GetString("TransferView_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TransferView_Cancel {
            get {
                return ResourceManager.GetString("TransferView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TransferView_Comment {
            get {
                return ResourceManager.GetString("TransferView_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TransferView_Date {
            get {
                return ResourceManager.GetString("TransferView_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        public static string TransferView_From_Account {
            get {
                return ResourceManager.GetString("TransferView_From_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TransferView_Save {
            get {
                return ResourceManager.GetString("TransferView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        public static string TransferView_To_Account {
            get {
                return ResourceManager.GetString("TransferView_To_Account", resourceCulture);
            }
        }
    }
}
